name: Update Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install xmlstarlet
      run: |
        sudo timedatectl set-timezone Asia/Shanghai
        sudo apt-get install -y xmlstarlet

    - name: Generate a file
      run: |
        chmod +x ./readme/update.sh
        ./readme/update.sh

    - name: Commit and push changes
      run: |
        git diff
        git config --global user.email "mail@yangfei.site"
        git config --global user.name "geekip"
        git add README.md
        git commit -m "update Readme"
        git push
