name: Update GFW

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' #UTC-8=6

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3.1.0

      - name: 准备环境
        run: |
          sudo apt update
          sudo timedatectl set-timezone "Asia/Shanghai"

      - name: 下载列表
        run: |
          # 局域网地址
          curl -sSL "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list" > cn.txt
          # 苹果中国
          curl -sSL "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list" >> cn.txt
          # 谷歌中国
          # curl -sSL "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list" >> cn.txt
          # 微软中国
          curl -sSL "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list" >> cn.txt
          echo "">> cn.txt
          # 中国云服务商ip段
          curl -sSL "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list" >> cn.txt
          # 中国媒体
          curl -sSL "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list" >> cn.txt
          # 中国域名
          curl -sSL "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list" >> cn.txt
          # 中国IP
          curl -sSL "https://www.ipdeny.com/ipblocks/data/aggregated/cn-aggregated.zone" | perl -ne '/(.+\/\d+)/ && print "IP-CIDR,$1,no-resolve\n"' >> cn.txt

          # 解析合并白名单
          declare -A files  
          files[DOMAIN]="domain.yaml"  
          files[DOMAIN-SUFFIX]="domain_suffix.yaml"  
          files[DOMAIN-KEYWORD]="keyword.yaml"
          files[IP-CIDR]="ip.yaml"  
            
          : > "${files[DOMAIN]}"  
          : > "${files[DOMAIN-SUFFIX]}"  
          : > "${files[DOMAIN-KEYWORD]}"  
          : > "${files[IP-CIDR]}"  

          while IFS=',' read -r prefix value; do  
            if [[ -n "$prefix" && -n "${files[$prefix]}" ]]; then  
              file="${files[$prefix]}"
              if [[ "$prefix" == "IP-CIDR"* ]]; then  
                value=$(echo "$value" | cut -d',' -f1)
                if [[ $value =~ ([0-9.]+)/([0-9]+) ]]; then  
                  ip=${BASH_REMATCH[1]}  
                  prefix_length=${BASH_REMATCH[2]}  
                  echo "- [$ip,$prefix_length]" >> "$file"
                fi
              else
                echo "- $value" >> "$file"
              fi     
            fi  
          done < cn.txt

          mkdir -p gfw
          echo ""> gfw/cn.json
          yq -o json -I 0 -i 'load("'${files[DOMAIN]}'") as $f | .domain=$f ' gfw/cn.json
          yq -o json -I 0 -i 'load("'${files[DOMAIN-SUFFIX]}'") as $f | .domain_suffix=$f ' gfw/cn.json
          yq -o json -I 0 -i 'load("'${files[DOMAIN-KEYWORD]}'") as $f | .keyword=$f ' gfw/cn.json
          yq -o json -I 0 -i 'load("'${files[IP-CIDR]}'") as $f | .ip=$f ' gfw/cn.json

      - name: 提交文件
        run: |
          cd ./gfw || exit 1
          git config --global user.email "mail@yangfei.site"
          git config --global user.name "geekip"
          git add .
          git commit -m "auto update"
          git push
