name: Update Pac Ruleset

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

env:
  local: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"
  cn_apple: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"
  cn_google: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list"
  cn_microsoft: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list"
  cn_company_ip: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list"
  cn_media: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list"
  cn_ip: "https://www.ipdeny.com/ipblocks/data/aggregated/cn-aggregated.zone"
  cn_domain: "https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/direct-list.txt"
  cn_domain_acl4: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"
  dist_dir: "gfw"
  src_cn: "cn.txt"
  dist_cn: "cn.json"
  dist_config: "config.json"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3.1.0

      - name: 准备环境
        run: |
          sudo apt update
          sudo timedatectl set-timezone "Asia/Shanghai"
          sudo apt-get install php php-yaml

      - name: 局域网地址
        run: |
          curl -sSL ${local} > ${{ env.src_cn }}

      - name: 苹果中国
        run: |
          curl -sSL ${cn_apple} >> ${{ env.src_cn }}

      - name: 谷歌中国
        run: |
          curl -sSL ${cn_google} >> ${{ env.src_cn }}

      - name: 微软中国
        run: |
          curl -sSL ${cn_microsoft} >> ${{ env.src_cn }}
          echo "">> ${{ env.src_cn }}

      - name: 中国云服务商ip段
        run: |
          curl -sSL ${cn_company_ip} >> ${{ env.src_cn }}

      - name: 中国媒体
        run: |
          curl -sSL ${cn_media} >> ${{ env.src_cn }}

      - name: 中国域名
        run: |
          curl -sSL ${cn_domain_acl4} >> ${{ env.src_cn }}

      - name: 中国IP
        run: |
          curl -sSL ${cn_ip} | perl -ne '/(.+\/\d+)/ && print "IP-CIDR,$1,no-resolve\n"' >> ${{ env.src_cn }}

      - name: 解析合并
        run: |
          declare -A files  
          files[DOMAIN]="domain.yaml"  
          files[DOMAIN-SUFFIX]="domain_suffix.yaml"  
          files[DOMAIN-KEYWORD]="keyword.yaml"  
          files[IP-CIDR]="ip.yaml"  
            
          : > "${files[DOMAIN]}"  
          : > "${files[DOMAIN-SUFFIX]}"  
          : > "${files[DOMAIN-KEYWORD]}"  
          : > "${files[IP-CIDR]}"  

          while IFS=',' read -r prefix value; do  
            if [[ -n "$prefix" && -n "${files[$prefix]}" ]]; then  
              file="${files[$prefix]}"
              if [[ "$prefix" == "IP-CIDR"* ]]; then  
                value=$(echo "$value" | cut -d',' -f1)
                if [[ $value =~ ([0-9.]+)/([0-9]+) ]]; then  
                  ip=${BASH_REMATCH[1]}  
                  prefix_length=${BASH_REMATCH[2]}  
                  echo "- [$ip,$prefix_length]" >> "$file"
                fi
              else
                echo "- $value" >> "$file"
              fi     
            fi  
          done < "${{ env.src_cn }}"

          echo ""> ${{ env.dist_cn }}
          yq -o json -I 0 -i 'load("domain.yaml") as $f | .domain=$f ' ${{ env.dist_cn }}
          yq -o json -I 0 -i 'load("domain_suffix.yaml") as $f | .domain_suffix=$f ' ${{ env.dist_cn }}
          yq -o json -I 0 -i 'load("keyword.yaml") as $f | .keyword=$f ' ${{ env.dist_cn }}
          yq -o json -I 0 -i 'load("ip.yaml") as $f | .ip=$f ' ${{ env.dist_cn }}

      # - name: Generate cn_domain
      #   run: |
      #     curl -sSL ${cn_domain} | grep -Ev "^(regexp|keyword):" | perl -ne '/^(full:)([-_a-zA-Z0-9]+(\.[-_a-zA-Z0-9]+)*)/ && print "- $2\n"' >> domain.yaml
      #     curl -sSL ${cn_domain} | grep -Ev "^(regexp|keyword|full):" | perl -ne '/^(domain:)?([-_a-zA-Z0-9]+(\.[-_a-zA-Z0-9]+)*)/ && print "- $2\n"' >> domain.yaml
      - name: 输出config.json文件
        run: |
          feedurl=$(php -r "echo urlencode('${{ secrets.GFW_FEED_URL }}');")
          key=$(php -r "echo urlencode('${{ secrets.GFW_KEY }}');")
          index=./${{ env.dist_dir }}/index.php
          chmod +x $index
          php $index feedurl=$feedurl key=$key
          mkdir -p ${{ env.dist_dir }}
          cp ${{ env.dist_config }} ${{ env.dist_dir }}

      - name: 提交文件
        run: |
          cd ${{ env.dist_dir }} || exit 1
          git config --global user.email "mail@yangfei.site"
          git config --global user.name "geekip"
          git add .
          git commit -m "auto update"
          git push

      - name: 推送到jsdelivr CDN
        run: |
          cd ${{ env.dist_dir }} || exit 1
          curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@main/${{ env.dist_dir }}/${{ env.dist_config }}"