name: Update GFW

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

env:
  LOCAL_URL: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"
  CN_APPLE_URL: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"
  CN_GOOGLE_URL: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list"
  CN_MICROSOFT_URL: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list"
  CN_COMPANY_IP_URL: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list"
  CN_MEDIA_URL: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list"
  CN_IP_URL: "https://www.ipdeny.com/ipblocks/data/aggregated/cn-aggregated.zone"
  CN_DOMAIN_URL: "https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/direct-list.txt"
  CN_DOMAIN_ACL4_URL: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"
  DIST_DIR: "gfw"
  SRC_CN: "cn.txt"
  DIST_CN: "cn.json"
  DIST_CONFIG: "config"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3.1.0

      - name: 准备环境
        run: |
          sudo apt update
          sudo timedatectl set-timezone "Asia/Shanghai"

      - name: 安装PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: yaml

      

      - name: 解析合并
        run: |
          echo "<?php define('FEED_URL', '${{ secrets.GFW_FEED_URL }}');define('KEY', '${{ secrets.GFW_KEY }}');require_once '${GITHUB_WORKSPACE}/gfw/index.php';?>" > run.php 

      # - name: Generate CN_DOMAIN_URL
      #   run: |
      #     curl -sSL ${CN_DOMAIN_URL} | grep -Ev "^(regexp|keyword):" | perl -ne '/^(full:)([-_a-zA-Z0-9]+(\.[-_a-zA-Z0-9]+)*)/ && print "- $2\n"' >> domain.yaml
      #     curl -sSL ${CN_DOMAIN_URL} | grep -Ev "^(regexp|keyword|full):" | perl -ne '/^(domain:)?([-_a-zA-Z0-9]+(\.[-_a-zA-Z0-9]+)*)/ && print "- $2\n"' >> domain.yaml
      - name: 解析配置
        run: php run.php

      - name: 提交文件
        run: |
          mkdir -p ${{ env.DIST_DIR }}
          ls -R
