name: Update GFW

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

env:
  WORKSPACE: "./gfw"
  CACHE_DIR: "./gfw/.cache"
  GFW_FEED_URL: "${{secrets.GFW_FEED_URL}}"
  GFW_EN_TYPE: "${{secrets.GFW_EN_TYPE}}"
  GFW_KEY: "${{secrets.GFW_KEY}}"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3.1.0

      - name: 准备环境
        run: |
          sudo apt update
          sudo timedatectl set-timezone "Asia/Shanghai"

      - name: 安装PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: yaml

      - name: 执行脚本
        run: |
          chmod +x ${{env.WORKSPACE}}/start.sh
          bash ${{env.WORKSPACE}}/start.sh

      - name: 提交文件
        run: |
          rm -rf ${{env.CACHE_DIR}}
          cd ${{env.WORKSPACE}} || exit 1
          git config --global user.email "mail@yangfei.site"
          git config --global user.name "geekip"
          git add .
          git commit -m "auto update"
          git push
